# Generated by Django 3.0.1 on 2020-01-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pink_salt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='permalink',
            field=models.CharField(default='/', max_length=12, unique=True),
        ),
    ]
