# Generated by Django 3.0.1 on 2020-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DurationField(verbose_name='Cooking Time')),
                ('serves', models.BigIntegerField(verbose_name='Serves')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('directions', models.TextField(verbose_name='Cooking Directions')),
                ('category', models.CharField(choices=[('A', 'Appetizer'), ('E', 'Entree'), ('S', 'Sides'), ('M', 'Main Course'), ('D', 'Dessert'), ('B', 'Beverage'), ('O', 'Other')], max_length=40)),
                ('coverimage', models.ImageField(upload_to='coverimages/')),
            ],
        ),
    ]
